spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server.url: ${SERVER_URL}
domain.url: ${DOMAIN_URL}
jwt.secret: ${JWT_SECRET}
jwt.expiration: ${JWT_EXPIRATION}

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ap-northeast-2
    bucket: todocbucket
    qr-path: qr

app:
  qr:
    base-url: ${QR_BASE_URL}

springdoc:
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web : DEBUG