spring:
  application:
    name: todoc
  #porfiles
  profiles:
    active: ${PROFILE:local}

  jackson:
    time-zone: Asia/Seoul
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8